set_property SRC_FILE_INFO {cfile:C:/Users/j48s677/Desktop/AES/arch4/vivado_proj/AES_one_round/AES_one_round.srcs/constrs_1/imports/resilient_hydra/constraints_hydra.xdc rfile:../../../AES_one_round.srcs/constrs_1/imports/resilient_hydra/constraints_hydra.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports i_clk]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports i_reset_n]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list i_clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 128 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ciphertext[0]} {ciphertext[1]} {ciphertext[2]} {ciphertext[3]} {ciphertext[4]} {ciphertext[5]} {ciphertext[6]} {ciphertext[7]} {ciphertext[8]} {ciphertext[9]} {ciphertext[10]} {ciphertext[11]} {ciphertext[12]} {ciphertext[13]} {ciphertext[14]} {ciphertext[15]} {ciphertext[16]} {ciphertext[17]} {ciphertext[18]} {ciphertext[19]} {ciphertext[20]} {ciphertext[21]} {ciphertext[22]} {ciphertext[23]} {ciphertext[24]} {ciphertext[25]} {ciphertext[26]} {ciphertext[27]} {ciphertext[28]} {ciphertext[29]} {ciphertext[30]} {ciphertext[31]} {ciphertext[32]} {ciphertext[33]} {ciphertext[34]} {ciphertext[35]} {ciphertext[36]} {ciphertext[37]} {ciphertext[38]} {ciphertext[39]} {ciphertext[40]} {ciphertext[41]} {ciphertext[42]} {ciphertext[43]} {ciphertext[44]} {ciphertext[45]} {ciphertext[46]} {ciphertext[47]} {ciphertext[48]} {ciphertext[49]} {ciphertext[50]} {ciphertext[51]} {ciphertext[52]} {ciphertext[53]} {ciphertext[54]} {ciphertext[55]} {ciphertext[56]} {ciphertext[57]} {ciphertext[58]} {ciphertext[59]} {ciphertext[60]} {ciphertext[61]} {ciphertext[62]} {ciphertext[63]} {ciphertext[64]} {ciphertext[65]} {ciphertext[66]} {ciphertext[67]} {ciphertext[68]} {ciphertext[69]} {ciphertext[70]} {ciphertext[71]} {ciphertext[72]} {ciphertext[73]} {ciphertext[74]} {ciphertext[75]} {ciphertext[76]} {ciphertext[77]} {ciphertext[78]} {ciphertext[79]} {ciphertext[80]} {ciphertext[81]} {ciphertext[82]} {ciphertext[83]} {ciphertext[84]} {ciphertext[85]} {ciphertext[86]} {ciphertext[87]} {ciphertext[88]} {ciphertext[89]} {ciphertext[90]} {ciphertext[91]} {ciphertext[92]} {ciphertext[93]} {ciphertext[94]} {ciphertext[95]} {ciphertext[96]} {ciphertext[97]} {ciphertext[98]} {ciphertext[99]} {ciphertext[100]} {ciphertext[101]} {ciphertext[102]} {ciphertext[103]} {ciphertext[104]} {ciphertext[105]} {ciphertext[106]} {ciphertext[107]} {ciphertext[108]} {ciphertext[109]} {ciphertext[110]} {ciphertext[111]} {ciphertext[112]} {ciphertext[113]} {ciphertext[114]} {ciphertext[115]} {ciphertext[116]} {ciphertext[117]} {ciphertext[118]} {ciphertext[119]} {ciphertext[120]} {ciphertext[121]} {ciphertext[122]} {ciphertext[123]} {ciphertext[124]} {ciphertext[125]} {ciphertext[126]} {ciphertext[127]}]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {key_idx[0]} {key_idx[1]}]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {pt_idx[0]} {pt_idx[1]} {pt_idx[2]}]]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list in_valid]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list key_load]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list key_valid]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list out_valid]]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets i_clk_IBUF_BUFG]
